### ISSUE TITLE
issue getting rest api to open

### ISSUE THREAD

**Issue by fitzjohnit** [IL2HorusTeam/il2fb-ds-airbridge#1]
this looks like some brilliant work, but having a couple issues getting things going.

using fresh ubuntu-16.04.4 and wine-3.0. used pyenv to install python 3.6.2 then installed the il2fd-ds-airbridge package via pip3

my confs.ini is

```
[NET]
serverName=Test
serverDescription=Test Server
checkRuntime=0
checkServerTimeSpeed=1
checkClientTimeSpeed=0
checkTimeSpeedDifferense=0.2
checkTimeSpeedInterval=17.0
localHost=176.126.241.115
localPort=21000
serverChannels=128
speed=25000
socksHost=
socksPort=1080
socksUser=
socksPwd=
allowMorseAsText=1
reflyDisabled=0
reflyKIADelay=0
reflyKIADelayMultiplier=0.0
maxAllowedKIA=-1
disableNetStatStatistics=0
showPilotNumber=1
showPilotPing=1
showPilotName=1
showPilotArmy=1
showPilotACDesignation=1
showPilotACType=1
showPilotScore=1
showTeamScore=1
cumulativeTeamScore=0
difficulty=6330221519999
SkinDownload=0
allowCustomSounds=0
filterUserNames=0

[MaxLag]
nearMaxLagTime=2.0
farMaxLagTime=10.0
cheaterWarningNum=3
cheaterWarningDelay=10.0

[Console]
IP=20000
IPS=localhost
LOG=1
LOGFILE=log.lst
LOGTIME=1
LOGKEEP=1
HISTORYCMD=128
HISTORY=128

[DeviceLink]
port=10000
host=localhost
IPS=

[chat]
autoLogDetail=3

[game]
eventlog=eventlog.lst
eventlogkeep=1
eventlogHouse=1
NoMissionInfoHud=0
noKillInfoHud=0
lowInfoHud=1
ShowMorseAsText=1
BlockMorseChat=0
SmallMapWPLabels=1
SkipParatrooperViews=1
TypeClouds=1
```

my airbridge.yml is:

```
ds:
  exe_path: /home/il2/il2ds/il2server.exe
  is_interactive: no
logging:
  files:
    main:
      level: debug
      file_path: airbridge.log
      keep_after_restart: yes
      is_delayed: no
    exceptions:
      file_path: airbridge.exc
      keep_after_restart: yes
      is_delayed: no
  rotation:
      is_enabled: yes
      max_size: 10485760
      max_backups: 10
  trace: yes
  encoding: utf8
  use_local_time: no
api:
  http:
    bind:
      port: 5000
      address: 176.126.241.115
streaming:
  chat:
    subscribers:
      file:
        args:
          path: /var/log/il2ds/streaming/chat
  events:
    subscribers:
      file:
        args:
          path: /var/log/il2ds/streaming/events
  not_parsed_strings:
    subscribers:
      file:
        args:
          path: /var/log/il2ds/streaming/not_parsed_strings
  radar:
    subscribers:
      file:
        args:
          path: /var/log/il2ds/streaming/radar
        subscription_options:
          refresh_period: 30
```

it fires up the server, but not getting anything in the log files (have checked permissions) and connection refused on the REST api. Not seemingly getting an open port 5000.

```
netstat -tulpn
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:111             0.0.0.0:*               LISTEN      174/rpcbind     
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      28157/sshd      
tcp        0      0 0.0.0.0:25              0.0.0.0:*               LISTEN      28640/master    
tcp        0      0 176.126.241.115:20000   0.0.0.0:*               LISTEN      23937/il2server.exe
tcp6       0      0 :::111                  :::*                    LISTEN      174/rpcbind     
tcp6       0      0 :::22                   :::*                    LISTEN      28157/sshd      
tcp6       0      0 :::25                   :::*                    LISTEN      28640/master    
udp        0      0 0.0.0.0:111             0.0.0.0:*                           174/rpcbind     
udp        0      0 0.0.0.0:774             0.0.0.0:*                           174/rpcbind     
udp        0      0 176.126.241.115:21000   0.0.0.0:*                           23937/il2server.exe
udp        0      0 127.0.0.1:10000         0.0.0.0:*                           23937/il2server.exe
udp6       0      0 :::111                  :::*                                174/rpcbind     
udp6       0      0 :::774                  :::*                                174/rpcbind 
```

I've tried running as both the il2 user i created, but also I did via root as well (using pyenv) but no luck yet. Any thoughts?

Thanks for your time and help.

**Comment by o3bvv** [comment]
Hi,

Thanks for your feedback! I'm glad you've found airdbrige to be useful.

1. Could you tell whether you can start bare DS without airbridge and connect to its console via telnet, e.g. `telnet 176.126.241.115 20000`?

2. Next, you config contains relative paths to log files, which means they will be created in current working directory. 

> not getting anything in the log files

Are those files created and just stay empty or they don't get created at all?

3. Finally, try to run airdbrige with `is_interactive` config option set to `yes` and see what output it will produce if any.

**Comment by fitzjohnit** [comment]
Hello,

Thanks for helping take a look. 

1. Tried this without airbridge and can connect. I can also connect this way with airbridge running as well.

2. They don't  get created, I've adjust the path to check that as well, e.g. just leaving as "path: events" etc and don't get created either. Entries are getting created in eventlog.lst as normal though.

3. Get server output as normal. I can connect with player etc too.

**Comment by o3bvv** [comment]
Well, that sounds wierd and right now I don't have a quick solution for the issue.

Logging is the first thing which is done after config file is read. The `is_delayed: no` option tells the app to create log files immediately. The whole app would crash if something goes wrong here, but this does not happen, as start of DS is done after setup of logging and both stages pass successfully.

So, let's find out what's wrong with logs at first and try to start airbridge with minimal interactive config:

``` yaml
state:
  file_path: /tmp/airbridge.state
ds:
  exe_path: /home/il2/il2ds/il2server.exe
  is_interactive: yes
logging:
  files:
    main:
      level: debug
      file_path: /tmp/airbridge.log
      keep_after_restart: yes
      is_delayed: no
    exceptions:
      file_path: /tmp/airbridge.exc
      keep_after_restart: yes
      is_delayed: no
  rotation:
      is_enabled: yes
      max_size: 10485760
      max_backups: 10
```

So, please:

1. Start airbridge with config listed above: ``il2fb-ds-airbridge -c /path/to/the/config.file``.
2. See whether any ``airbridge*`` file is present inside ``/tmp`` directory: ``ls -lah /tmp/airbridge*``.

It is expected for 3 files to be created there:

1. ``airbridge.state``
2. ``airbridge.log``
3. ``airbridge.exc``

Let me know, if this test passes.

p.s. Are you running your system on a bare metal or inside a VM/container?
p.p.s. If files are not created, but DS starts running and is fully operatable, does its console output contain colored command numbers like in the example (see below) or all output has the same color?


<img src="https://github.com/IL2HorusTeam/il2fb-ds-airbridge/raw/master/docs/Runtime.png" width="400px" alt="output example">

**Comment by fitzjohnit** [comment]
Been playing around a bit more. It seems that actually the issue is related to wine.  Originally had used the official wine repository and installed winehq-stable giving me version 3.0.0. It's worth noting that with wine 3.0.0 I can still run the game directly just not with il2fb-ds-airbridge. The latter gave me the following output when running on VirtualBox Ubuntu environment

```
0009:err:winsock:interface_bind Failed to bind to interface, receiving broadcast packets will not work on socket 0300.
0009:err:winsock:interface_bind Failed to bind to interface, receiving broadcast packets will not work on socket 03f0.
1>mission LOAD net/dogfight/3/1_Islands.mis BEGIN
Loading mission net/dogfight/3/1_Islands.mis...
Load bridges
Load static objects
Mission: net/dogfight/3/1_Islands.mis is Playing
1>f gc.cmd
>GC
Memory: total(17563648) free(1056608)
>GC
Memory: total(17498112) free(1002808)
>GC
Memory: total(17498112) free(1034328)
>timeout 3600000 f gc.cmd
7>004f:fixme:ntdll:server_ioctl_file Unsupported ioctl 11400c (device=11 access=1 func=3 method=0)
```


I downgraded to both wine 1.8 and 1.6 on other environments and running il2fb-ds-airbridge everything appears to be working as should. HTTP API, log files etc. 

NB I also double checked with wine 3.0.0 on my laptop and couldn't get it to run, going back to 1.8 worked. I did this to try and rule out any issue with virtualisation.

**Comment by o3bvv** [comment]
Great to hear that 🙂Thanks for investigation!
